// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: blocks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlock = `-- name: CreateBlock :one
INSERT INTO layout_blocks (name, category, description, objects_json, preview_svg)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, category, description, objects_json, preview_svg, created_at, updated_at
`

type CreateBlockParams struct {
	Name        string      `db:"name"`
	Category    string      `db:"category"`
	Description pgtype.Text `db:"description"`
	ObjectsJson string      `db:"objects_json"`
	PreviewSvg  pgtype.Text `db:"preview_svg"`
}

type CreateBlockRow struct {
	ID          int32              `db:"id"`
	Name        string             `db:"name"`
	Category    string             `db:"category"`
	Description pgtype.Text        `db:"description"`
	ObjectsJson string             `db:"objects_json"`
	PreviewSvg  pgtype.Text        `db:"preview_svg"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (CreateBlockRow, error) {
	row := q.db.QueryRow(ctx, createBlock,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.ObjectsJson,
		arg.PreviewSvg,
	)
	var i CreateBlockRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.ObjectsJson,
		&i.PreviewSvg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :execrows
DELETE FROM layout_blocks WHERE id = $1
`

func (q *Queries) DeleteBlock(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlock, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBlocks = `-- name: ListBlocks :many
SELECT id, name, category, COALESCE(description, '')::TEXT as description, objects_json, COALESCE(preview_svg, '')::TEXT as preview_svg, created_at, updated_at
FROM layout_blocks
ORDER BY updated_at DESC
`

type ListBlocksRow struct {
	ID          int32              `db:"id"`
	Name        string             `db:"name"`
	Category    string             `db:"category"`
	Description string             `db:"description"`
	ObjectsJson string             `db:"objects_json"`
	PreviewSvg  string             `db:"preview_svg"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) ListBlocks(ctx context.Context) ([]ListBlocksRow, error) {
	rows, err := q.db.Query(ctx, listBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlocksRow
	for rows.Next() {
		var i ListBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.ObjectsJson,
			&i.PreviewSvg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
