// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: components.sql

package db

import (
	"context"
)

const createComponent = `-- name: CreateComponent :one
INSERT INTO global_components (id, label, asset_type, view_box, default_w, default_h, svg_markup)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, label, asset_type, view_box, default_w, default_h, svg_markup, created_at, updated_at
`

type CreateComponentParams struct {
	ID        string  `db:"id"`
	Label     string  `db:"label"`
	AssetType string  `db:"asset_type"`
	ViewBox   string  `db:"view_box"`
	DefaultW  float64 `db:"default_w"`
	DefaultH  float64 `db:"default_h"`
	SvgMarkup string  `db:"svg_markup"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (GlobalComponent, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.ID,
		arg.Label,
		arg.AssetType,
		arg.ViewBox,
		arg.DefaultW,
		arg.DefaultH,
		arg.SvgMarkup,
	)
	var i GlobalComponent
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AssetType,
		&i.ViewBox,
		&i.DefaultW,
		&i.DefaultH,
		&i.SvgMarkup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :execrows
DELETE FROM global_components WHERE id = $1
`

func (q *Queries) DeleteComponent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComponent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listComponents = `-- name: ListComponents :many
SELECT id, label, asset_type, view_box, default_w, default_h, svg_markup, created_at, updated_at
FROM global_components
ORDER BY label
`

func (q *Queries) ListComponents(ctx context.Context) ([]GlobalComponent, error) {
	rows, err := q.db.Query(ctx, listComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalComponent
	for rows.Next() {
		var i GlobalComponent
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.AssetType,
			&i.ViewBox,
			&i.DefaultW,
			&i.DefaultH,
			&i.SvgMarkup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertComponent = `-- name: UpsertComponent :one
INSERT INTO global_components (id, label, asset_type, view_box, default_w, default_h, svg_markup)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE
  SET label = EXCLUDED.label,
      asset_type = EXCLUDED.asset_type,
      view_box = EXCLUDED.view_box,
      default_w = EXCLUDED.default_w,
      default_h = EXCLUDED.default_h,
      svg_markup = EXCLUDED.svg_markup,
      updated_at = NOW()
RETURNING id, label, asset_type, view_box, default_w, default_h, svg_markup, created_at, updated_at
`

type UpsertComponentParams struct {
	ID        string  `db:"id"`
	Label     string  `db:"label"`
	AssetType string  `db:"asset_type"`
	ViewBox   string  `db:"view_box"`
	DefaultW  float64 `db:"default_w"`
	DefaultH  float64 `db:"default_h"`
	SvgMarkup string  `db:"svg_markup"`
}

func (q *Queries) UpsertComponent(ctx context.Context, arg UpsertComponentParams) (GlobalComponent, error) {
	row := q.db.QueryRow(ctx, upsertComponent,
		arg.ID,
		arg.Label,
		arg.AssetType,
		arg.ViewBox,
		arg.DefaultW,
		arg.DefaultH,
		arg.SvgMarkup,
	)
	var i GlobalComponent
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AssetType,
		&i.ViewBox,
		&i.DefaultW,
		&i.DefaultH,
		&i.SvgMarkup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
