// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: desks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDesk = `-- name: DeleteDesk :execrows
DELETE FROM desks WHERE id = $1
`

func (q *Queries) DeleteDesk(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDesk, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeskByID = `-- name: GetDeskByID :one
SELECT id, floor_id, label, type, space_type, assigned_to, position_x, position_y, w, h, qr_token
FROM desks
WHERE id = $1
`

func (q *Queries) GetDeskByID(ctx context.Context, id int32) (Desk, error) {
	row := q.db.QueryRow(ctx, getDeskByID, id)
	var i Desk
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Label,
		&i.Type,
		&i.SpaceType,
		&i.AssignedTo,
		&i.PositionX,
		&i.PositionY,
		&i.W,
		&i.H,
		&i.QrToken,
	)
	return i, err
}

const listDesks = `-- name: ListDesks :many
SELECT id, floor_id, label, type, space_type, assigned_to, position_x, position_y, w, h, qr_token
FROM desks
ORDER BY id
`

func (q *Queries) ListDesks(ctx context.Context) ([]Desk, error) {
	rows, err := q.db.Query(ctx, listDesks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Desk
	for rows.Next() {
		var i Desk
		if err := rows.Scan(
			&i.ID,
			&i.FloorID,
			&i.Label,
			&i.Type,
			&i.SpaceType,
			&i.AssignedTo,
			&i.PositionX,
			&i.PositionY,
			&i.W,
			&i.H,
			&i.QrToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDesksByFloor = `-- name: ListDesksByFloor :many
SELECT id, floor_id, label, type, space_type, assigned_to, position_x, position_y, w, h, qr_token
FROM desks
WHERE floor_id = $1
ORDER BY id
`

func (q *Queries) ListDesksByFloor(ctx context.Context, floorID int32) ([]Desk, error) {
	rows, err := q.db.Query(ctx, listDesksByFloor, floorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Desk
	for rows.Next() {
		var i Desk
		if err := rows.Scan(
			&i.ID,
			&i.FloorID,
			&i.Label,
			&i.Type,
			&i.SpaceType,
			&i.AssignedTo,
			&i.PositionX,
			&i.PositionY,
			&i.W,
			&i.H,
			&i.QrToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDesk = `-- name: UpdateDesk :one
UPDATE desks
SET label = COALESCE($2, label),
    type = COALESCE($3, type),
    space_type = COALESCE($4, space_type),
    assigned_to = COALESCE($5, assigned_to),
    position_x = COALESCE($6, position_x),
    position_y = COALESCE($7, position_y),
    w = COALESCE($8, w),
    h = COALESCE($9, h)
WHERE id = $1
RETURNING id, floor_id, label, type, space_type, assigned_to, position_x, position_y, w, h, qr_token
`

type UpdateDeskParams struct {
	ID         int32         `db:"id"`
	Label      pgtype.Text   `db:"label"`
	Type       pgtype.Text   `db:"type"`
	SpaceType  pgtype.Text   `db:"space_type"`
	AssignedTo pgtype.Text   `db:"assigned_to"`
	PositionX  pgtype.Float8 `db:"position_x"`
	PositionY  pgtype.Float8 `db:"position_y"`
	W          pgtype.Float8 `db:"w"`
	H          pgtype.Float8 `db:"h"`
}

func (q *Queries) UpdateDesk(ctx context.Context, arg UpdateDeskParams) (Desk, error) {
	row := q.db.QueryRow(ctx, updateDesk,
		arg.ID,
		arg.Label,
		arg.Type,
		arg.SpaceType,
		arg.AssignedTo,
		arg.PositionX,
		arg.PositionY,
		arg.W,
		arg.H,
	)
	var i Desk
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Label,
		&i.Type,
		&i.SpaceType,
		&i.AssignedTo,
		&i.PositionX,
		&i.PositionY,
		&i.W,
		&i.H,
		&i.QrToken,
	)
	return i, err
}
