// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: floors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkOfficeExists = `-- name: CheckOfficeExists :one
SELECT EXISTS(SELECT 1 FROM offices WHERE id = $1)
`

func (q *Queries) CheckOfficeExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, checkOfficeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createFloor = `-- name: CreateFloor :one
INSERT INTO floors (office_id, name)
VALUES ($1, $2)
RETURNING id, office_id, name, plan_url
`

type CreateFloorParams struct {
	OfficeID int32  `db:"office_id"`
	Name     string `db:"name"`
}

type CreateFloorRow struct {
	ID       int32       `db:"id"`
	OfficeID int32       `db:"office_id"`
	Name     string      `db:"name"`
	PlanUrl  pgtype.Text `db:"plan_url"`
}

func (q *Queries) CreateFloor(ctx context.Context, arg CreateFloorParams) (CreateFloorRow, error) {
	row := q.db.QueryRow(ctx, createFloor, arg.OfficeID, arg.Name)
	var i CreateFloorRow
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.PlanUrl,
	)
	return i, err
}

const deleteFloor = `-- name: DeleteFloor :execrows
DELETE FROM floors WHERE id = $1
`

func (q *Queries) DeleteFloor(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFloor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFloors = `-- name: ListFloors :many
SELECT id, office_id, name, plan_url FROM floors ORDER BY id
`

type ListFloorsRow struct {
	ID       int32       `db:"id"`
	OfficeID int32       `db:"office_id"`
	Name     string      `db:"name"`
	PlanUrl  pgtype.Text `db:"plan_url"`
}

func (q *Queries) ListFloors(ctx context.Context) ([]ListFloorsRow, error) {
	rows, err := q.db.Query(ctx, listFloors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFloorsRow
	for rows.Next() {
		var i ListFloorsRow
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.Name,
			&i.PlanUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloorsByOffice = `-- name: ListFloorsByOffice :many
SELECT id, office_id, name, plan_url FROM floors WHERE office_id = $1 ORDER BY id
`

type ListFloorsByOfficeRow struct {
	ID       int32       `db:"id"`
	OfficeID int32       `db:"office_id"`
	Name     string      `db:"name"`
	PlanUrl  pgtype.Text `db:"plan_url"`
}

func (q *Queries) ListFloorsByOffice(ctx context.Context, officeID int32) ([]ListFloorsByOfficeRow, error) {
	rows, err := q.db.Query(ctx, listFloorsByOffice, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFloorsByOfficeRow
	for rows.Next() {
		var i ListFloorsByOfficeRow
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.Name,
			&i.PlanUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFloorPlanURL = `-- name: SetFloorPlanURL :execrows
UPDATE floors
SET plan_url = $2
WHERE id = $1
`

type SetFloorPlanURLParams struct {
	ID      int32       `db:"id"`
	PlanUrl pgtype.Text `db:"plan_url"`
}

func (q *Queries) SetFloorPlanURL(ctx context.Context, arg SetFloorPlanURLParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFloorPlanURL, arg.ID, arg.PlanUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFloor = `-- name: UpdateFloor :one
UPDATE floors
SET name = COALESCE($2, name)
WHERE id = $1
RETURNING id, office_id, name, plan_url
`

type UpdateFloorParams struct {
	ID   int32       `db:"id"`
	Name pgtype.Text `db:"name"`
}

type UpdateFloorRow struct {
	ID       int32       `db:"id"`
	OfficeID int32       `db:"office_id"`
	Name     string      `db:"name"`
	PlanUrl  pgtype.Text `db:"plan_url"`
}

func (q *Queries) UpdateFloor(ctx context.Context, arg UpdateFloorParams) (UpdateFloorRow, error) {
	row := q.db.QueryRow(ctx, updateFloor, arg.ID, arg.Name)
	var i UpdateFloorRow
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.Name,
		&i.PlanUrl,
	)
	return i, err
}
