// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (token, email, role, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token, email, role, created_by, created_at, expires_at, used_at
`

type CreateInviteParams struct {
	Token     string             `db:"token"`
	Email     string             `db:"email"`
	Role      string             `db:"role"`
	CreatedBy pgtype.Int4        `db:"created_by"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.Token,
		arg.Email,
		arg.Role,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, token, email, role, created_by, created_at, expires_at, used_at
FROM invites
WHERE token = $1
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, token, email, role, created_by, created_at, expires_at, used_at
FROM invites
ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Email,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invites
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkInviteUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markInviteUsed, id)
	return err
}
