// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: layouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveRevision = `-- name: ArchiveRevision :exec
UPDATE floor_map_revisions SET status = 'archived', updated_at = now() WHERE id = $1
`

func (q *Queries) ArchiveRevision(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, archiveRevision, id)
	return err
}

const cleanupArchivedRevisions = `-- name: CleanupArchivedRevisions :execrows
DELETE FROM floor_map_revisions
WHERE status = 'archived' AND updated_at < $1
AND id NOT IN (
  SELECT COALESCE(published_map_revision_id, 0) FROM floors
  UNION
  SELECT COALESCE(draft_map_revision_id, 0) FROM floors
)
`

func (q *Queries) CleanupArchivedRevisions(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupArchivedRevisions, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearFloorDraftRevision = `-- name: ClearFloorDraftRevision :exec
UPDATE floors SET draft_map_revision_id = NULL WHERE id = $1
`

func (q *Queries) ClearFloorDraftRevision(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, clearFloorDraftRevision, id)
	return err
}

const deleteExpiredLockForFloor = `-- name: DeleteExpiredLockForFloor :exec
DELETE FROM floor_locks WHERE floor_id = $1 AND expires_at <= $2
`

type DeleteExpiredLockForFloorParams struct {
	FloorID   int32              `db:"floor_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) DeleteExpiredLockForFloor(ctx context.Context, arg DeleteExpiredLockForFloorParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredLockForFloor, arg.FloorID, arg.ExpiresAt)
	return err
}

const deleteExpiredLocks = `-- name: DeleteExpiredLocks :exec
DELETE FROM floor_locks WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredLocks(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredLocks, expiresAt)
	return err
}

const deleteRevision = `-- name: DeleteRevision :exec
DELETE FROM floor_map_revisions WHERE id = $1
`

func (q *Queries) DeleteRevision(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRevision, id)
	return err
}

const getAuditHistory = `-- name: GetAuditHistory :many
SELECT id, floor_id, user_id, action, revision_id, created_at, note
FROM map_audit_log
WHERE floor_id = $1
ORDER BY id DESC
LIMIT $2
`

type GetAuditHistoryParams struct {
	FloorID int32 `db:"floor_id"`
	Limit   int32 `db:"limit"`
}

func (q *Queries) GetAuditHistory(ctx context.Context, arg GetAuditHistoryParams) ([]MapAuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditHistory, arg.FloorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapAuditLog
	for rows.Next() {
		var i MapAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.FloorID,
			&i.UserID,
			&i.Action,
			&i.RevisionID,
			&i.CreatedAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredLocks = `-- name: GetExpiredLocks :many
SELECT floor_id FROM floor_locks WHERE expires_at <= $1
`

func (q *Queries) GetExpiredLocks(ctx context.Context, expiresAt pgtype.Timestamptz) ([]int32, error) {
	rows, err := q.db.Query(ctx, getExpiredLocks, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var floor_id int32
		if err := rows.Scan(&floor_id); err != nil {
			return nil, err
		}
		items = append(items, floor_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFloorRefs = `-- name: GetFloorRefs :one
SELECT id, published_map_revision_id, draft_map_revision_id FROM floors WHERE id = $1
`

type GetFloorRefsRow struct {
	ID                     int32       `db:"id"`
	PublishedMapRevisionID pgtype.Int4 `db:"published_map_revision_id"`
	DraftMapRevisionID     pgtype.Int4 `db:"draft_map_revision_id"`
}

func (q *Queries) GetFloorRefs(ctx context.Context, id int32) (GetFloorRefsRow, error) {
	row := q.db.QueryRow(ctx, getFloorRefs, id)
	var i GetFloorRefsRow
	err := row.Scan(&i.ID, &i.PublishedMapRevisionID, &i.DraftMapRevisionID)
	return i, err
}

const getFloorRefsForUpdate = `-- name: GetFloorRefsForUpdate :one
SELECT id, published_map_revision_id, draft_map_revision_id FROM floors WHERE id = $1 FOR UPDATE
`

type GetFloorRefsForUpdateRow struct {
	ID                     int32       `db:"id"`
	PublishedMapRevisionID pgtype.Int4 `db:"published_map_revision_id"`
	DraftMapRevisionID     pgtype.Int4 `db:"draft_map_revision_id"`
}

func (q *Queries) GetFloorRefsForUpdate(ctx context.Context, id int32) (GetFloorRefsForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getFloorRefsForUpdate, id)
	var i GetFloorRefsForUpdateRow
	err := row.Scan(&i.ID, &i.PublishedMapRevisionID, &i.DraftMapRevisionID)
	return i, err
}

const getLayoutRevision = `-- name: GetLayoutRevision :one
SELECT id, floor_id, status, version, created_at, updated_at, published_at, created_by, layout_json, semantic_svg
FROM floor_map_revisions
WHERE id = $1
`

type GetLayoutRevisionRow struct {
	ID          int32              `db:"id"`
	FloorID     int32              `db:"floor_id"`
	Status      string             `db:"status"`
	Version     int32              `db:"version"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
	LayoutJson  pgtype.Text        `db:"layout_json"`
	SemanticSvg pgtype.Text        `db:"semantic_svg"`
}

func (q *Queries) GetLayoutRevision(ctx context.Context, id int32) (GetLayoutRevisionRow, error) {
	row := q.db.QueryRow(ctx, getLayoutRevision, id)
	var i GetLayoutRevisionRow
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.LayoutJson,
		&i.SemanticSvg,
	)
	return i, err
}

const getLayoutRevisionForUpdate = `-- name: GetLayoutRevisionForUpdate :one
SELECT id, floor_id, status, version, created_at, updated_at, published_at, created_by, layout_json, semantic_svg
FROM floor_map_revisions
WHERE id = $1 FOR UPDATE
`

type GetLayoutRevisionForUpdateRow struct {
	ID          int32              `db:"id"`
	FloorID     int32              `db:"floor_id"`
	Status      string             `db:"status"`
	Version     int32              `db:"version"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
	LayoutJson  pgtype.Text        `db:"layout_json"`
	SemanticSvg pgtype.Text        `db:"semantic_svg"`
}

func (q *Queries) GetLayoutRevisionForUpdate(ctx context.Context, id int32) (GetLayoutRevisionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLayoutRevisionForUpdate, id)
	var i GetLayoutRevisionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.LayoutJson,
		&i.SemanticSvg,
	)
	return i, err
}

const getLock = `-- name: GetLock :one
SELECT l.floor_id, l.locked_by, COALESCE(u.username, '')::TEXT as username, l.locked_at, l.expires_at
FROM floor_locks l
LEFT JOIN users u ON u.id = l.locked_by
WHERE l.floor_id = $1
`

type GetLockRow struct {
	FloorID   int32              `db:"floor_id"`
	LockedBy  int32              `db:"locked_by"`
	Username  string             `db:"username"`
	LockedAt  pgtype.Timestamptz `db:"locked_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) GetLock(ctx context.Context, floorID int32) (GetLockRow, error) {
	row := q.db.QueryRow(ctx, getLock, floorID)
	var i GetLockRow
	err := row.Scan(
		&i.FloorID,
		&i.LockedBy,
		&i.Username,
		&i.LockedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLockForUpdate = `-- name: GetLockForUpdate :one
SELECT l.floor_id, l.locked_by, COALESCE(u.username, '')::TEXT as username, l.locked_at, l.expires_at
FROM floor_locks l
LEFT JOIN users u ON u.id = l.locked_by
WHERE l.floor_id = $1
FOR UPDATE OF l
`

type GetLockForUpdateRow struct {
	FloorID   int32              `db:"floor_id"`
	LockedBy  int32              `db:"locked_by"`
	Username  string             `db:"username"`
	LockedAt  pgtype.Timestamptz `db:"locked_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) GetLockForUpdate(ctx context.Context, floorID int32) (GetLockForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLockForUpdate, floorID)
	var i GetLockForUpdateRow
	err := row.Scan(
		&i.FloorID,
		&i.LockedBy,
		&i.Username,
		&i.LockedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRevisionDataForRestore = `-- name: GetRevisionDataForRestore :one
SELECT floor_id, plan_svg, desks_json, zones_json, layout_json
FROM floor_map_revisions
WHERE id = $1 FOR UPDATE
`

type GetRevisionDataForRestoreRow struct {
	FloorID    int32       `db:"floor_id"`
	PlanSvg    pgtype.Text `db:"plan_svg"`
	DesksJson  string      `db:"desks_json"`
	ZonesJson  string      `db:"zones_json"`
	LayoutJson pgtype.Text `db:"layout_json"`
}

func (q *Queries) GetRevisionDataForRestore(ctx context.Context, id int32) (GetRevisionDataForRestoreRow, error) {
	row := q.db.QueryRow(ctx, getRevisionDataForRestore, id)
	var i GetRevisionDataForRestoreRow
	err := row.Scan(
		&i.FloorID,
		&i.PlanSvg,
		&i.DesksJson,
		&i.ZonesJson,
		&i.LayoutJson,
	)
	return i, err
}

const insertDeskForSync = `-- name: InsertDeskForSync :exec
INSERT INTO desks (floor_id, label, type, space_type, assigned_to, position_x, position_y, w, h, qr_token)
VALUES ($1, $2, $3, 'desk', $4, $5, $6, $7, $8, $9)
`

type InsertDeskForSyncParams struct {
	FloorID    int32         `db:"floor_id"`
	Label      string        `db:"label"`
	Type       string        `db:"type"`
	AssignedTo pgtype.Text   `db:"assigned_to"`
	PositionX  pgtype.Float8 `db:"position_x"`
	PositionY  pgtype.Float8 `db:"position_y"`
	W          float64       `db:"w"`
	H          float64       `db:"h"`
	QrToken    string        `db:"qr_token"`
}

func (q *Queries) InsertDeskForSync(ctx context.Context, arg InsertDeskForSyncParams) error {
	_, err := q.db.Exec(ctx, insertDeskForSync,
		arg.FloorID,
		arg.Label,
		arg.Type,
		arg.AssignedTo,
		arg.PositionX,
		arg.PositionY,
		arg.W,
		arg.H,
		arg.QrToken,
	)
	return err
}

const insertDraftForRestore = `-- name: InsertDraftForRestore :one
INSERT INTO floor_map_revisions (floor_id, status, plan_svg, desks_json, zones_json, layout_json, semantic_svg, version, created_by)
VALUES ($1, 'draft', $2, COALESCE($3, '[]'), COALESCE($4, '[]'), $5, NULL, $6, $7)
RETURNING id, floor_id, status, version, created_at, updated_at, published_at, created_by, layout_json, semantic_svg
`

type InsertDraftForRestoreParams struct {
	FloorID    int32       `db:"floor_id"`
	PlanSvg    pgtype.Text `db:"plan_svg"`
	Column3    interface{} `db:"column_3"`
	Column4    interface{} `db:"column_4"`
	LayoutJson pgtype.Text `db:"layout_json"`
	Version    int32       `db:"version"`
	CreatedBy  pgtype.Int4 `db:"created_by"`
}

type InsertDraftForRestoreRow struct {
	ID          int32              `db:"id"`
	FloorID     int32              `db:"floor_id"`
	Status      string             `db:"status"`
	Version     int32              `db:"version"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
	LayoutJson  pgtype.Text        `db:"layout_json"`
	SemanticSvg pgtype.Text        `db:"semantic_svg"`
}

func (q *Queries) InsertDraftForRestore(ctx context.Context, arg InsertDraftForRestoreParams) (InsertDraftForRestoreRow, error) {
	row := q.db.QueryRow(ctx, insertDraftForRestore,
		arg.FloorID,
		arg.PlanSvg,
		arg.Column3,
		arg.Column4,
		arg.LayoutJson,
		arg.Version,
		arg.CreatedBy,
	)
	var i InsertDraftForRestoreRow
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.LayoutJson,
		&i.SemanticSvg,
	)
	return i, err
}

const insertDraftLayout = `-- name: InsertDraftLayout :one
INSERT INTO floor_map_revisions (floor_id, status, desks_json, zones_json, layout_json, semantic_svg, version, created_by)
VALUES ($1, 'draft', '[]', '[]', $2, NULL, $3, $4)
RETURNING id, floor_id, status, version, created_at, updated_at, published_at, created_by, layout_json, semantic_svg
`

type InsertDraftLayoutParams struct {
	FloorID    int32       `db:"floor_id"`
	LayoutJson pgtype.Text `db:"layout_json"`
	Version    int32       `db:"version"`
	CreatedBy  pgtype.Int4 `db:"created_by"`
}

type InsertDraftLayoutRow struct {
	ID          int32              `db:"id"`
	FloorID     int32              `db:"floor_id"`
	Status      string             `db:"status"`
	Version     int32              `db:"version"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
	LayoutJson  pgtype.Text        `db:"layout_json"`
	SemanticSvg pgtype.Text        `db:"semantic_svg"`
}

func (q *Queries) InsertDraftLayout(ctx context.Context, arg InsertDraftLayoutParams) (InsertDraftLayoutRow, error) {
	row := q.db.QueryRow(ctx, insertDraftLayout,
		arg.FloorID,
		arg.LayoutJson,
		arg.Version,
		arg.CreatedBy,
	)
	var i InsertDraftLayoutRow
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.LayoutJson,
		&i.SemanticSvg,
	)
	return i, err
}

const insertLock = `-- name: InsertLock :one
INSERT INTO floor_locks (floor_id, locked_by, locked_at, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING floor_id, locked_by, locked_at, expires_at
`

type InsertLockParams struct {
	FloorID   int32              `db:"floor_id"`
	LockedBy  int32              `db:"locked_by"`
	LockedAt  pgtype.Timestamptz `db:"locked_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

type InsertLockRow struct {
	FloorID   int32              `db:"floor_id"`
	LockedBy  int32              `db:"locked_by"`
	LockedAt  pgtype.Timestamptz `db:"locked_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) InsertLock(ctx context.Context, arg InsertLockParams) (InsertLockRow, error) {
	row := q.db.QueryRow(ctx, insertLock,
		arg.FloorID,
		arg.LockedBy,
		arg.LockedAt,
		arg.ExpiresAt,
	)
	var i InsertLockRow
	err := row.Scan(
		&i.FloorID,
		&i.LockedBy,
		&i.LockedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExistingDesksForSync = `-- name: ListExistingDesksForSync :many
SELECT id, label, qr_token FROM desks WHERE floor_id = $1
`

type ListExistingDesksForSyncRow struct {
	ID      int32  `db:"id"`
	Label   string `db:"label"`
	QrToken string `db:"qr_token"`
}

func (q *Queries) ListExistingDesksForSync(ctx context.Context, floorID int32) ([]ListExistingDesksForSyncRow, error) {
	rows, err := q.db.Query(ctx, listExistingDesksForSync, floorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExistingDesksForSyncRow
	for rows.Next() {
		var i ListExistingDesksForSyncRow
		if err := rows.Scan(&i.ID, &i.Label, &i.QrToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT r.id, r.floor_id, r.status, r.version, r.created_at, r.updated_at, r.published_at, r.created_by, u.username
FROM floor_map_revisions r
LEFT JOIN users u ON u.id = r.created_by
WHERE r.floor_id = $1
ORDER BY r.id DESC
LIMIT $2
`

type ListRevisionsParams struct {
	FloorID int32 `db:"floor_id"`
	Limit   int32 `db:"limit"`
}

type ListRevisionsRow struct {
	ID          int32              `db:"id"`
	FloorID     int32              `db:"floor_id"`
	Status      string             `db:"status"`
	Version     int32              `db:"version"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
	Username    pgtype.Text        `db:"username"`
}

func (q *Queries) ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]ListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listRevisions, arg.FloorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionsRow
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.FloorID,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAudit = `-- name: LogAudit :exec
INSERT INTO map_audit_log (floor_id, user_id, action, revision_id, note)
VALUES ($1, $2, $3, $4, $5)
`

type LogAuditParams struct {
	FloorID    int32       `db:"floor_id"`
	UserID     pgtype.Int4 `db:"user_id"`
	Action     string      `db:"action"`
	RevisionID pgtype.Int4 `db:"revision_id"`
	Note       pgtype.Text `db:"note"`
}

func (q *Queries) LogAudit(ctx context.Context, arg LogAuditParams) error {
	_, err := q.db.Exec(ctx, logAudit,
		arg.FloorID,
		arg.UserID,
		arg.Action,
		arg.RevisionID,
		arg.Note,
	)
	return err
}

const publishRevision = `-- name: PublishRevision :one
UPDATE floor_map_revisions
SET semantic_svg = $2, status = 'published', published_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, floor_id, status, version, created_at, updated_at, published_at, created_by, layout_json, semantic_svg
`

type PublishRevisionParams struct {
	ID          int32       `db:"id"`
	SemanticSvg pgtype.Text `db:"semantic_svg"`
}

type PublishRevisionRow struct {
	ID          int32              `db:"id"`
	FloorID     int32              `db:"floor_id"`
	Status      string             `db:"status"`
	Version     int32              `db:"version"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
	LayoutJson  pgtype.Text        `db:"layout_json"`
	SemanticSvg pgtype.Text        `db:"semantic_svg"`
}

func (q *Queries) PublishRevision(ctx context.Context, arg PublishRevisionParams) (PublishRevisionRow, error) {
	row := q.db.QueryRow(ctx, publishRevision, arg.ID, arg.SemanticSvg)
	var i PublishRevisionRow
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.LayoutJson,
		&i.SemanticSvg,
	)
	return i, err
}

const releaseLock = `-- name: ReleaseLock :exec
DELETE FROM floor_locks WHERE floor_id = $1 AND locked_by = $2
`

type ReleaseLockParams struct {
	FloorID  int32 `db:"floor_id"`
	LockedBy int32 `db:"locked_by"`
}

func (q *Queries) ReleaseLock(ctx context.Context, arg ReleaseLockParams) error {
	_, err := q.db.Exec(ctx, releaseLock, arg.FloorID, arg.LockedBy)
	return err
}

const setFloorDraftRevision = `-- name: SetFloorDraftRevision :exec
UPDATE floors SET draft_map_revision_id = $2 WHERE id = $1
`

type SetFloorDraftRevisionParams struct {
	ID                 int32       `db:"id"`
	DraftMapRevisionID pgtype.Int4 `db:"draft_map_revision_id"`
}

func (q *Queries) SetFloorDraftRevision(ctx context.Context, arg SetFloorDraftRevisionParams) error {
	_, err := q.db.Exec(ctx, setFloorDraftRevision, arg.ID, arg.DraftMapRevisionID)
	return err
}

const setFloorPublishedRevision = `-- name: SetFloorPublishedRevision :exec
UPDATE floors SET published_map_revision_id = $2, draft_map_revision_id = NULL WHERE id = $1
`

type SetFloorPublishedRevisionParams struct {
	ID                     int32       `db:"id"`
	PublishedMapRevisionID pgtype.Int4 `db:"published_map_revision_id"`
}

func (q *Queries) SetFloorPublishedRevision(ctx context.Context, arg SetFloorPublishedRevisionParams) error {
	_, err := q.db.Exec(ctx, setFloorPublishedRevision, arg.ID, arg.PublishedMapRevisionID)
	return err
}

const updateDeskForSync = `-- name: UpdateDeskForSync :exec
UPDATE desks
SET label = $2,
    type = $3,
    space_type = 'desk',
    assigned_to = $4,
    position_x = $5,
    position_y = $6,
    w = $7,
    h = $8,
    qr_token = COALESCE(NULLIF(qr_token, ''), $9)
WHERE id = $1
`

type UpdateDeskForSyncParams struct {
	ID         int32         `db:"id"`
	Label      string        `db:"label"`
	Type       string        `db:"type"`
	AssignedTo pgtype.Text   `db:"assigned_to"`
	PositionX  pgtype.Float8 `db:"position_x"`
	PositionY  pgtype.Float8 `db:"position_y"`
	W          float64       `db:"w"`
	H          float64       `db:"h"`
	QrToken    string        `db:"qr_token"`
}

func (q *Queries) UpdateDeskForSync(ctx context.Context, arg UpdateDeskForSyncParams) error {
	_, err := q.db.Exec(ctx, updateDeskForSync,
		arg.ID,
		arg.Label,
		arg.Type,
		arg.AssignedTo,
		arg.PositionX,
		arg.PositionY,
		arg.W,
		arg.H,
		arg.QrToken,
	)
	return err
}

const updateDraftForRestore = `-- name: UpdateDraftForRestore :one
UPDATE floor_map_revisions
SET status = 'draft',
    plan_svg = $2,
    desks_json = COALESCE($3, '[]'),
    zones_json = COALESCE($4, '[]'),
    layout_json = $5,
    semantic_svg = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, floor_id, status, version, created_at, updated_at, published_at, created_by, layout_json, semantic_svg
`

type UpdateDraftForRestoreParams struct {
	ID         int32       `db:"id"`
	PlanSvg    pgtype.Text `db:"plan_svg"`
	DesksJson  string      `db:"desks_json"`
	ZonesJson  string      `db:"zones_json"`
	LayoutJson pgtype.Text `db:"layout_json"`
}

type UpdateDraftForRestoreRow struct {
	ID          int32              `db:"id"`
	FloorID     int32              `db:"floor_id"`
	Status      string             `db:"status"`
	Version     int32              `db:"version"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
	LayoutJson  pgtype.Text        `db:"layout_json"`
	SemanticSvg pgtype.Text        `db:"semantic_svg"`
}

func (q *Queries) UpdateDraftForRestore(ctx context.Context, arg UpdateDraftForRestoreParams) (UpdateDraftForRestoreRow, error) {
	row := q.db.QueryRow(ctx, updateDraftForRestore,
		arg.ID,
		arg.PlanSvg,
		arg.DesksJson,
		arg.ZonesJson,
		arg.LayoutJson,
	)
	var i UpdateDraftForRestoreRow
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.LayoutJson,
		&i.SemanticSvg,
	)
	return i, err
}

const updateDraftLayout = `-- name: UpdateDraftLayout :one
UPDATE floor_map_revisions
SET layout_json = $2, semantic_svg = NULL, status = 'draft', updated_at = now()
WHERE id = $1
RETURNING id, floor_id, status, version, created_at, updated_at, published_at, created_by, layout_json, semantic_svg
`

type UpdateDraftLayoutParams struct {
	ID         int32       `db:"id"`
	LayoutJson pgtype.Text `db:"layout_json"`
}

type UpdateDraftLayoutRow struct {
	ID          int32              `db:"id"`
	FloorID     int32              `db:"floor_id"`
	Status      string             `db:"status"`
	Version     int32              `db:"version"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
	LayoutJson  pgtype.Text        `db:"layout_json"`
	SemanticSvg pgtype.Text        `db:"semantic_svg"`
}

func (q *Queries) UpdateDraftLayout(ctx context.Context, arg UpdateDraftLayoutParams) (UpdateDraftLayoutRow, error) {
	row := q.db.QueryRow(ctx, updateDraftLayout, arg.ID, arg.LayoutJson)
	var i UpdateDraftLayoutRow
	err := row.Scan(
		&i.ID,
		&i.FloorID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.LayoutJson,
		&i.SemanticSvg,
	)
	return i, err
}

const updateLock = `-- name: UpdateLock :one
UPDATE floor_locks
SET locked_by = $2, locked_at = $3, expires_at = $4
WHERE floor_id = $1
RETURNING floor_id, locked_by, locked_at, expires_at
`

type UpdateLockParams struct {
	FloorID   int32              `db:"floor_id"`
	LockedBy  int32              `db:"locked_by"`
	LockedAt  pgtype.Timestamptz `db:"locked_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

type UpdateLockRow struct {
	FloorID   int32              `db:"floor_id"`
	LockedBy  int32              `db:"locked_by"`
	LockedAt  pgtype.Timestamptz `db:"locked_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) UpdateLock(ctx context.Context, arg UpdateLockParams) (UpdateLockRow, error) {
	row := q.db.QueryRow(ctx, updateLock,
		arg.FloorID,
		arg.LockedBy,
		arg.LockedAt,
		arg.ExpiresAt,
	)
	var i UpdateLockRow
	err := row.Scan(
		&i.FloorID,
		&i.LockedBy,
		&i.LockedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSemanticSVG = `-- name: UpdateSemanticSVG :exec
UPDATE floor_map_revisions
SET semantic_svg = $2, updated_at = now()
WHERE id = $1
`

type UpdateSemanticSVGParams struct {
	ID          int32       `db:"id"`
	SemanticSvg pgtype.Text `db:"semantic_svg"`
}

func (q *Queries) UpdateSemanticSVG(ctx context.Context, arg UpdateSemanticSVGParams) error {
	_, err := q.db.Exec(ctx, updateSemanticSVG, arg.ID, arg.SemanticSvg)
	return err
}
