// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Desk struct {
	ID         int32         `db:"id"`
	FloorID    int32         `db:"floor_id"`
	Label      string        `db:"label"`
	Type       string        `db:"type"`
	SpaceType  string        `db:"space_type"`
	AssignedTo pgtype.Text   `db:"assigned_to"`
	PositionX  pgtype.Float8 `db:"position_x"`
	PositionY  pgtype.Float8 `db:"position_y"`
	W          float64       `db:"w"`
	H          float64       `db:"h"`
	QrToken    string        `db:"qr_token"`
}

type Floor struct {
	ID                     int32       `db:"id"`
	OfficeID               int32       `db:"office_id"`
	Name                   string      `db:"name"`
	PlanUrl                pgtype.Text `db:"plan_url"`
	PublishedMapRevisionID pgtype.Int4 `db:"published_map_revision_id"`
	DraftMapRevisionID     pgtype.Int4 `db:"draft_map_revision_id"`
}

type FloorLock struct {
	ID        int32              `db:"id"`
	FloorID   int32              `db:"floor_id"`
	LockedBy  int32              `db:"locked_by"`
	LockedAt  pgtype.Timestamptz `db:"locked_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

type FloorMapRevision struct {
	ID          int32              `db:"id"`
	FloorID     int32              `db:"floor_id"`
	Status      string             `db:"status"`
	PlanSvg     pgtype.Text        `db:"plan_svg"`
	DesksJson   string             `db:"desks_json"`
	ZonesJson   string             `db:"zones_json"`
	Version     int32              `db:"version"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
	LayoutJson  pgtype.Text        `db:"layout_json"`
	SemanticSvg pgtype.Text        `db:"semantic_svg"`
}

type GlobalComponent struct {
	ID        string             `db:"id"`
	Label     string             `db:"label"`
	AssetType string             `db:"asset_type"`
	ViewBox   string             `db:"view_box"`
	DefaultW  float64            `db:"default_w"`
	DefaultH  float64            `db:"default_h"`
	SvgMarkup string             `db:"svg_markup"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}

type Invite struct {
	ID        int32              `db:"id"`
	Token     string             `db:"token"`
	Email     string             `db:"email"`
	Role      string             `db:"role"`
	CreatedBy pgtype.Int4        `db:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at"`
}

type LayoutBlock struct {
	ID          int32              `db:"id"`
	Name        string             `db:"name"`
	Category    string             `db:"category"`
	Description pgtype.Text        `db:"description"`
	ObjectsJson string             `db:"objects_json"`
	PreviewSvg  pgtype.Text        `db:"preview_svg"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
}

type LayoutTemplate struct {
	ID          int32              `db:"id"`
	Name        string             `db:"name"`
	Description pgtype.Text        `db:"description"`
	Category    string             `db:"category"`
	LayoutJson  string             `db:"layout_json"`
	PreviewSvg  pgtype.Text        `db:"preview_svg"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	CreatedBy   pgtype.Int4        `db:"created_by"`
}

type MapAuditLog struct {
	ID         int32              `db:"id"`
	FloorID    int32              `db:"floor_id"`
	UserID     pgtype.Int4        `db:"user_id"`
	Action     string             `db:"action"`
	RevisionID pgtype.Int4        `db:"revision_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	Note       pgtype.Text        `db:"note"`
}

type Office struct {
	ID      int32       `db:"id"`
	Name    string      `db:"name"`
	Address pgtype.Text `db:"address"`
}

type User struct {
	ID             int32       `db:"id"`
	Username       string      `db:"username"`
	Email          string      `db:"email"`
	HashedPassword string      `db:"hashed_password"`
	Role           string      `db:"role"`
	CreatedAt      pgtype.Date `db:"created_at"`
	FullName       pgtype.Text `db:"full_name"`
	Department     pgtype.Text `db:"department"`
	Position       pgtype.Text `db:"position"`
	Phone          pgtype.Text `db:"phone"`
	UserStatus     string      `db:"user_status"`
	IsActive       bool        `db:"is_active"`
}
