// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: offices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOffice = `-- name: CreateOffice :one
INSERT INTO offices (name, address)
VALUES ($1, $2)
RETURNING id, name, address
`

type CreateOfficeParams struct {
	Name    string      `db:"name"`
	Address pgtype.Text `db:"address"`
}

func (q *Queries) CreateOffice(ctx context.Context, arg CreateOfficeParams) (Office, error) {
	row := q.db.QueryRow(ctx, createOffice, arg.Name, arg.Address)
	var i Office
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}

const deleteOffice = `-- name: DeleteOffice :execrows
DELETE FROM offices WHERE id = $1
`

func (q *Queries) DeleteOffice(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOffice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOffices = `-- name: ListOffices :many
SELECT id, name, address FROM offices ORDER BY id
`

func (q *Queries) ListOffices(ctx context.Context) ([]Office, error) {
	rows, err := q.db.Query(ctx, listOffices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Office
	for rows.Next() {
		var i Office
		if err := rows.Scan(&i.ID, &i.Name, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOffice = `-- name: UpdateOffice :one
UPDATE offices
SET name = COALESCE($2, name),
    address = COALESCE($3, address)
WHERE id = $1
RETURNING id, name, address
`

type UpdateOfficeParams struct {
	ID      int32       `db:"id"`
	Name    pgtype.Text `db:"name"`
	Address pgtype.Text `db:"address"`
}

func (q *Queries) UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (Office, error) {
	row := q.db.QueryRow(ctx, updateOffice, arg.ID, arg.Name, arg.Address)
	var i Office
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}
