// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveRevision(ctx context.Context, id int32) error
	CheckOfficeExists(ctx context.Context, id int32) (bool, error)
	CleanupArchivedRevisions(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error)
	ClearFloorDraftRevision(ctx context.Context, id int32) error
	CreateBlock(ctx context.Context, arg CreateBlockParams) (CreateBlockRow, error)
	CreateComponent(ctx context.Context, arg CreateComponentParams) (GlobalComponent, error)
	CreateFloor(ctx context.Context, arg CreateFloorParams) (CreateFloorRow, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreateOffice(ctx context.Context, arg CreateOfficeParams) (Office, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (CreateTemplateRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBlock(ctx context.Context, id int32) (int64, error)
	DeleteComponent(ctx context.Context, id string) (int64, error)
	DeleteDesk(ctx context.Context, id int32) (int64, error)
	DeleteExpiredLockForFloor(ctx context.Context, arg DeleteExpiredLockForFloorParams) error
	DeleteExpiredLocks(ctx context.Context, expiresAt pgtype.Timestamptz) error
	DeleteFloor(ctx context.Context, id int32) (int64, error)
	DeleteInvite(ctx context.Context, id int32) (int64, error)
	DeleteOffice(ctx context.Context, id int32) (int64, error)
	DeleteRevision(ctx context.Context, id int32) error
	DeleteTemplate(ctx context.Context, id int32) (int64, error)
	DeleteUser(ctx context.Context, username string) (int64, error)
	GetAuditHistory(ctx context.Context, arg GetAuditHistoryParams) ([]MapAuditLog, error)
	GetDeskByID(ctx context.Context, id int32) (Desk, error)
	GetExpiredLocks(ctx context.Context, expiresAt pgtype.Timestamptz) ([]int32, error)
	GetFloorRefs(ctx context.Context, id int32) (GetFloorRefsRow, error)
	GetFloorRefsForUpdate(ctx context.Context, id int32) (GetFloorRefsForUpdateRow, error)
	GetInviteByToken(ctx context.Context, token string) (Invite, error)
	GetLayoutRevision(ctx context.Context, id int32) (GetLayoutRevisionRow, error)
	GetLayoutRevisionForUpdate(ctx context.Context, id int32) (GetLayoutRevisionForUpdateRow, error)
	GetLock(ctx context.Context, floorID int32) (GetLockRow, error)
	GetLockForUpdate(ctx context.Context, floorID int32) (GetLockForUpdateRow, error)
	GetRevisionDataForRestore(ctx context.Context, id int32) (GetRevisionDataForRestoreRow, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserEmailID(ctx context.Context, email string) (int32, error)
	InsertDeskForSync(ctx context.Context, arg InsertDeskForSyncParams) error
	InsertDraftForRestore(ctx context.Context, arg InsertDraftForRestoreParams) (InsertDraftForRestoreRow, error)
	InsertDraftLayout(ctx context.Context, arg InsertDraftLayoutParams) (InsertDraftLayoutRow, error)
	InsertLock(ctx context.Context, arg InsertLockParams) (InsertLockRow, error)
	ListBlocks(ctx context.Context) ([]ListBlocksRow, error)
	ListComponents(ctx context.Context) ([]GlobalComponent, error)
	ListDesks(ctx context.Context) ([]Desk, error)
	ListDesksByFloor(ctx context.Context, floorID int32) ([]Desk, error)
	ListExistingDesksForSync(ctx context.Context, floorID int32) ([]ListExistingDesksForSyncRow, error)
	ListFloors(ctx context.Context) ([]ListFloorsRow, error)
	ListFloorsByOffice(ctx context.Context, officeID int32) ([]ListFloorsByOfficeRow, error)
	ListInvites(ctx context.Context) ([]Invite, error)
	ListOffices(ctx context.Context) ([]Office, error)
	ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]ListRevisionsRow, error)
	ListTemplates(ctx context.Context) ([]ListTemplatesRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	LogAudit(ctx context.Context, arg LogAuditParams) error
	MarkInviteUsed(ctx context.Context, id int32) error
	PublishRevision(ctx context.Context, arg PublishRevisionParams) (PublishRevisionRow, error)
	ReleaseLock(ctx context.Context, arg ReleaseLockParams) error
	SetFloorDraftRevision(ctx context.Context, arg SetFloorDraftRevisionParams) error
	SetFloorPlanURL(ctx context.Context, arg SetFloorPlanURLParams) (int64, error)
	SetFloorPublishedRevision(ctx context.Context, arg SetFloorPublishedRevisionParams) error
	UpdateDesk(ctx context.Context, arg UpdateDeskParams) (Desk, error)
	UpdateDeskForSync(ctx context.Context, arg UpdateDeskForSyncParams) error
	UpdateDraftForRestore(ctx context.Context, arg UpdateDraftForRestoreParams) (UpdateDraftForRestoreRow, error)
	UpdateDraftLayout(ctx context.Context, arg UpdateDraftLayoutParams) (UpdateDraftLayoutRow, error)
	UpdateFloor(ctx context.Context, arg UpdateFloorParams) (UpdateFloorRow, error)
	UpdateLock(ctx context.Context, arg UpdateLockParams) (UpdateLockRow, error)
	UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (Office, error)
	UpdateSemanticSVG(ctx context.Context, arg UpdateSemanticSVGParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpsertComponent(ctx context.Context, arg UpsertComponentParams) (GlobalComponent, error)
}

var _ Querier = (*Queries)(nil)
