// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO layout_templates (name, description, category, layout_json)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, category, layout_json, created_at, updated_at
`

type CreateTemplateParams struct {
	Name        string      `db:"name"`
	Description pgtype.Text `db:"description"`
	Category    string      `db:"category"`
	LayoutJson  string      `db:"layout_json"`
}

type CreateTemplateRow struct {
	ID          int32              `db:"id"`
	Name        string             `db:"name"`
	Description pgtype.Text        `db:"description"`
	Category    string             `db:"category"`
	LayoutJson  string             `db:"layout_json"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (CreateTemplateRow, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.LayoutJson,
	)
	var i CreateTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.LayoutJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM layout_templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, COALESCE(description, '')::TEXT as description, category, layout_json, created_at, updated_at
FROM layout_templates
ORDER BY updated_at DESC
`

type ListTemplatesRow struct {
	ID          int32              `db:"id"`
	Name        string             `db:"name"`
	Description string             `db:"description"`
	Category    string             `db:"category"`
	LayoutJson  string             `db:"layout_json"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) ListTemplates(ctx context.Context) ([]ListTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplatesRow
	for rows.Next() {
		var i ListTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.LayoutJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
