// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, hashed_password, role)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, hashed_password, role, created_at, full_name, department, position, phone, user_status, is_active
`

type CreateUserParams struct {
	Username       string `db:"username"`
	Email          string `db:"email"`
	HashedPassword string `db:"hashed_password"`
	Role           string `db:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.Phone,
		&i.UserStatus,
		&i.IsActive,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, hashed_password, role, created_at, full_name, department, position, phone, user_status, is_active
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.Phone,
		&i.UserStatus,
		&i.IsActive,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, hashed_password, role, created_at, full_name, department, position, phone, user_status, is_active
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.Phone,
		&i.UserStatus,
		&i.IsActive,
	)
	return i, err
}

const getUserEmailID = `-- name: GetUserEmailID :one
SELECT id FROM users WHERE email = $1
`

func (q *Queries) GetUserEmailID(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, getUserEmailID, email)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, hashed_password, role, created_at, full_name, department, position, phone, user_status, is_active
FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.HashedPassword,
			&i.Role,
			&i.CreatedAt,
			&i.FullName,
			&i.Department,
			&i.Position,
			&i.Phone,
			&i.UserStatus,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, is_active = $3
WHERE username = $1
RETURNING id, username, email, hashed_password, role, created_at, full_name, department, position, phone, user_status, is_active
`

type UpdateUserRoleParams struct {
	Username string `db:"username"`
	Role     string `db:"role"`
	IsActive bool   `db:"is_active"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.Username, arg.Role, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.Phone,
		&i.UserStatus,
		&i.IsActive,
	)
	return i, err
}
